Feature/shopping cart
CristianSk23/PF-Client pull request #32
Opened 2023-11-30 23:06 UTC by matiaspiccirilli

ShoppingCart revisión 1

2023-11-30 23:38 UTC, matiaspiccirilli reviewed
Resolviendo Conflictos

2023-11-30 23:50 UTC, JFernandoLopez approved these changes

2023-12-01 04:04 UTC, BrunoxxG requested changes
revisar el div del srecren que te mando bel!

2023-12-02 21:33 UTC, DiegoZallo approved these changes

2023-12-02 21:36 UTC, DiegoZallo approved these changes

2023-12-02 23:30 UTC, BrunoxxG approved these changes

2023-12-02 23:30 UTC, merged