combined filters and orders rev2
CristianSk23/PF-Client pull request #9
Opened 2023-11-25 21:56 UTC by matiaspiccirilli

Ahí quedo funcionando ok el tema de filtros combinados, OBS:
1) hice un mix usando el código de Diego para los filtros y mantuve los Ordenamientos con el que ya tenía ya que funciona OK;
2) Modifique el tema de cambiar la palabra "ORDER" por "SORT";
3) quedaron todos los Select en la seccion de SearchBar;
4) hay un Bug en el botón de Reset que voy a tratar de solucionar lo antes posible (el botón resetea la lista desplegable de los orders pero no de los filters). No obstante, paso igual a PR para tener más tiempo de ir integrando todo

2023-11-25 23:23 UTC, diego1contreras approved these changes

2023-11-26 00:54 UTC, micaortiz requested changes
1. Verificar la importación en actions ya que SEARCHPRODUCTS esta importado 2 veces
2. Verificar la action order

2023-11-26 02:15 UTC, matiaspiccirilli reviewed
Corregidas Observaciones de la action order, y las dobles importaciones

2023-11-26 03:59 UTC, barufe approved these changes

2023-11-26 03:59 UTC, merged